### ISSUE TITLE
少量issue页我是手动保存为mhtml而非爬成html

### ISSUE THREAD

**Issue by dou4cc** [dou4cc/discuss_history#1]
firefox不支持，chrome还是支持的

问题是mime应该写成啥？
so上也没讲清：https://stackoverflow.com/questions/31250/content-type-for-mht-files

@xxnet

**Comment by dou4cc** [comment]
或者转成html？
我还不会，研究下

**Comment by xxnet** [comment]
​直觉是转比较简单

**Comment by dou4cc** [comment]
之所以说要研究下是因为chrome不能转。。

刚看了下，IE居然能转，效果还不错（惊喜

**Comment by dou4cc** [comment]
话说。。一个包含万把个文件改动的commit需要committing多久？我的github desktop居然僵住了！
